import { describe, test, expect } from "bun:test";
import { compileServer } from "../src/targets/compile-server.js";

// ─── compileServer ─────────────────────────────────────────────────────────

describe("compileServer", () => {
  test("returns null when no server entries exist", async () => {
    const doc = {
      tagName: "div",
      children: [{ tagName: "p", textContent: "No server entries" }],
    };
    const result = await compileServer(doc);
    expect(result).toBeNull();
  });

  test("generates Hono handler for server entries", async () => {
    const doc = {
      tagName: "div",
      state: {
        getData: {
          timing: "server",
          $src: "./api/get-data.js",
          $export: "getData",
        },
      },
      children: [],
    };
    const result = await compileServer(doc);
    expect(result).not.toBeNull();
    expect(result).toContain("import { Hono } from 'hono'");
    expect(result).toContain("import { getData } from './api/get-data.js'");
    expect(result).toContain("app.post('/_jx/server/getData'");
    expect(result).toContain("export default app");
  });

  test("supports custom baseUrl option", async () => {
    const doc = {
      state: {
        myFunc: {
          timing: "server",
          $src: "./handlers.js",
          $export: "myFunc",
        },
      },
    };
    const result = await compileServer(doc, { baseUrl: "/api" });
    expect(result).toContain("app.post('/api/myFunc'");
  });

  test("generates multiple routes for multiple server entries", async () => {
    const doc = {
      state: {
        fetchUser: {
          timing: "server",
          $src: "./user.js",
          $export: "fetchUser",
        },
        saveUser: {
          timing: "server",
          $src: "./user.js",
          $export: "saveUser",
        },
      },
    };
    const result = await compileServer(doc);
    expect(result).toContain("app.post('/_jx/server/fetchUser'");
    expect(result).toContain("app.post('/_jx/server/saveUser'");
    expect(result).toContain("import { fetchUser } from './user.js'");
    expect(result).toContain("import { saveUser } from './user.js'");
  });

  test("generated code includes json parsing", async () => {
    const doc = {
      state: {
        handler: {
          timing: "server",
          $src: "./api.js",
          $export: "handler",
        },
      },
    };
    const result = await compileServer(doc);
    expect(result).toContain("c.req.json()");
    expect(result).toContain("c.json(await handler(args))");
  });

  test("includes do-not-edit comment", async () => {
    const doc = {
      state: {
        fn: {
          timing: "server",
          $src: "./fn.js",
          $export: "fn",
        },
      },
    };
    const result = await compileServer(doc);
    expect(result).toContain("Generated by @jxsuite/compiler");
    expect(result).toContain("do not edit manually");
  });
});
